[settings]
cache_prune_age = "7d"

[tools]
### tools
lazygit = "latest"
fzf = "latest"
zoxide = "latest"
eza = "latest"
fd = "latest"
bat = "latest"
yazi = "latest"
ripgrep = "latest"
# ripgrep-all = "latest"
difftastic = "latest"
gdu = "latest"
tokei = "latest"
jq = "latest"
cargo-binstall = "latest"
tmux = "latest"
herdr = "latest"
lnav = "latest"
neovim = "latest"
jless = "latest"

### UI
starship = "latest"
glow = "latest"

### Languages
node = "lts"
uv = "latest"
elixir = "1.20"
erlang = "29"
rust = "latest"
go = "latest"
golangci-lint = "latest"
typst = "latest"
tree-sitter = "latest"

### Other stuff
# visidata                # not included
# tealdeer = "latest"     # not included
# delta = "latest"        # git diffs
# duf = "latest"          # df
# sd = "latest"           # sed
# just = "latest"         # make
# xh = "latest"           # curl
# fx = "latest"           # json
# yq = "latest"           # yaml
