[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run = "ouch"

# See https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml
# for defaults
# defaults to xdg-open on linux

[opener]
wslviewer = [
  { run = 'cmd.exe /C start "" "$(wslpath -w "$1")"', orphan = true, desc = "Open with Windows", for = "linux" },
]
# Need to disable security policy to open server files in Firefox
wslbrowser = [
  { run = 'chrome "$(wslpath -w "$1")"', orphan = true, desc = "Chrome", for = "linux" },
]

[open]
prepend_rules = [
  { url = "*.html", use = [
    "wslbrowser",
    "edit",
  ] },
  { url = "*.pdf", use = [
    "wslviewer",
    "edit",
  ] },
  { mime = "image/*", use = [
    "wslviewer",
    "edit",
  ] },
]
